language: node_js

# matrix:
#   include:
#   - node_js: '8'
#     os: osx
#     script: npm run test:integration
#   - node_js: '8'
#     sudo: required
#     os: linux
#     dist: trusty
#     addons:
#       chrome: stable
#       firefox: latest
#     before_script:
#     - export DISPLAY=:99.0
#     - sh -e /etc/init.d/xvfb start
#     script:
#     - npm run test:unit
#     - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sauce; fi
# env:
#   global:
#     - secure: C+/z9HB1amzxgntbpkNhjcWeYFt6uagVAp2TuceInyzCpwD8A9mOG+X3pfBX8A0OJnKchSduXbcUzcg8Rw2ZVR/RZajkzWUnInFNeFm4WMgHZFQxc+pHq9o5UyCw+Q237+S5IdC+WI0lfAGh3+5OeGvS+JoC3jUarYb6UlCybgfkqA+Zo0wy6Xyjisb3vYKPnmmF+Ki5fkzwLqpkcqQI3zZQZimTZHNwGOJO6ib2uEEjaCVhvG1XKDlF8M+07arE97hKOJEEKIHHPOaPtABw634OfwbiS5lPHlb626VD+ry08P1FH7mg3XM+XdUS7T+o3Lb2RScjA5jetF27s2E9mK467zIw60kC5e8eDx8/uJWlx/c3jT4nQQ+epjTp7M5lbOQBYiQttGureaWHSVVvUJKTrSN8CxceV7Zmia1N9dtC3o2CEDZyrbJ5+2tR8POkUZkz5XHNhHg0/U/vq0dm3LjhOGfyKCqD4o1qS2ytdzPVu2fwHdD63NxU1pKPeYNcO3aKASTgUJpPWA4j/JQWWNF/HTUU6NMO3ihKxX+ZeenX/wtvSrurNIFhIqf81hr0iRYVH+pMOZ7shfr65w6GgllQjO2gFz8IZyc0t9I5CJnOVyhHfgdVj4XgeTHaxDalYE/eB/ny1unxbG/c+6v06pHWJ9HNXFd5VXPTmtNu1m8=
#     - secure: MIqRhLuXEh4qKMvVnbqs2jAtwsGgnl8qLYRNGKeG5eUf3aJT86FJefcccddVAipNun10fnkSkNd2rpNb/G8Htxvyg9lYiOeCDOvxsaDtYwxvz1WGk2u5kRUjkfyb2LVzUV0MCUSiR+o/9qUXy5TVcwrzAN/4Jin8diMPVkuektP5xhyVm1BAMufn+IcX56xtkT123Egz1Y0N47TKB4rEqhVUazYvMy2Vq2Xs2NIpVT2v8+91UzRLCeESIKKPFfZvdgVHovqKiKmsXLMsGTsAKT6FjimSmKvknC4iR7B3CiQQwoo0GIJjd/QKy35S3wMUoZEy+WpN8hBuKoJLg2GtaVmsV1MEAyKBFtMRPQwUTSPSxz5RQzVYKby9TsOKulFbsfk1jRzAlJSc4USSXO7/HH/vcTF0NZJhqvZAo8mX43UqQSmOEo6vobEASM8I5lysQnuqjrDTowg8Wou7a0yhIaKiGBhf5Yy61mSqURNBXCpRHR75SDr2/9qtqU8hfH6PqCuLHtQ0eEhNzfcjo8fPRcAx2QWPmmnOpDAZcxFvVGlkiM5aOFlRiPbGLFADkzm1uDh7GYfSChoLoEhM/MJMxl0OeLIcKpsgXUjrQv2KdJCVtbu610jMlH98J5GsfoA7SkKUn8DYujkuhaHBqYKLjZ7tCVLXsoMZqJcQf7W5Q3g=

addons:
  artifacts:
    paths:
      - ./.firebaserc
      - ./firebase.json
      - ./server
      - ./functions

node_js: '8'

jobs:
  include:
    - stage: build
      name: Build
      os: linux
      dist: xenial
      install:
        - npm install
      script:
        - npm run build
        - npm run prune:production
    - stage: deploy
      name: Deploy
      if: branch = master
      script: skip
      deploy:
        provider: firebase
        token:
          secure: "e3+8PRmw7SkqHyT2VzqfIE+5+ckfFaMqfg/Nu6ygbwGnJTdUPwP9krnMIqNQqdblkj87Rf7AzbNL1aYZNeiAwQtDDyLHJiLzjKxwNU1ks+I5E0NsIdTDM7HWcHsFDWv/yUj5f+RrM5pPP5sirM6hZvcJETgLU9uke3ZNQhkZGjG2B/kTaqPHOy1xjb3jbehHn6hrrCbb4Fa6bL8h3/MJ7A/lN8eETeW/rvvi7924d2qaUjAg37nyDl9S8+3y9eMZzilMTvkWZDc47TRWYJw/JLSfzcK36ahgAm1pv8ilktWoL+NjuumkW5207ljfwmXZe/Gr4+kksbE0L7rtk8B037KRuhV27LLt5QnR8dFdMLKx4/ONL99IJZKjDnQi1DsGMkwmOCfgi3seiG/BeCT/RcD648wZoAXntUSyOsrsKqFFAPdJ4fsz8hPB3/z9fmltO8IURV+p5udT6gjVSOoDxnQqD6z7Qb63Wjef5BkfafgporJU/ByaX9LDWtsYpVb8jUdUEEU7D7D4pJI4Lcl7K8edMSx0CAw8kIPuVnN7O949tVWtMQwxF1N2MxG+eDKbrvvDE8Qeej+Vzs16JPepYlnG1QMxD8cJpyfzAJorKsL7tpJGAWcj7lUJXRJ2b/eqcYHNjsrgVZq6WvO3IPAsbBCu7Rd7tu22J/1LSkbP5Lo="
        skip_cleanup: true